device:
  name: cheetah

platform:
  product_makefile: device/google/pantah/aosp_cheetah.mk

includes:
  - snippets/2022.yml

filters:
  overlay_files:
    match:
      # Workaround for aapt2 output parsing bug
      - HbmSVManager__auto_generated_rro_product.apk
